---
- name: Create backup keypair
  openssh_keypair:
    path: "/root/.ssh/{{ backups_sh_key_filename }}"
    type: rsa

- name: Install backupninja package
  package:
    name: backupninja
    use: apt
    state: present

- name: Correct default config
  lineinfile:
    path: "/etc/backupninja.conf"
    search_string: "reportprom = false"
    line: "reportprom ="

- name: Setup backupninja config for app data
  template:
    src: ./templates/backupninja_rsync.conf
    dest: "{{ backup_confs_dir  }}/app_data.rsync"
    owner: root
    group: root
    mode: "660"
  vars:
    destination_host: "{{ backup_host }}"
    destination_user: "{{ backup_user }}"
    id_file: "/root/.ssh/{{ backups_sh_key_filename }}"
